openapi: 3.0.2
info:
  title: Issues Backend
  description: Microservice for issues
  version: 1.0.0
servers:
  - url: /api/v1
paths:
  /issues:
    get:
      description: Fetches all issues
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: object
                properties:
                  issues:
                    type: array
                    items:
                      $ref: "#/components/schemas/issueDto"

components:
  schemas:
    issueDto:
      example:
        id: 046b6c7f-0b8a-43b9-b35d-6489e6daee91
        title: email
        description: firstName
      type: object
      required:
        - id
        - title
        - description
      properties:
        id:
          type: string
          format: uuid
        title:
          type: string
        description:
          type: string
    error:
      type: object
      properties:
        message:
          type: string